import { call, check, summary, base } from "./lib.mjs";
let r = await call("POST", "/api/auth/login", { email: "matthew@cel.app", password: "celdemo" });
const token = r.json.token;
const pid = (await call("GET", "/api/projects", undefined, token)).json[0].id;
await call("POST", `/api/projects/${pid}/ai/key`, { key: "sk-real-key", model: "mock/model" }, token);
r = await call("POST", `/api/projects/${pid}/ai/agent/check`, { scriptContent: "Bingo walks." }, token);
check("agent check", r.status === 200 && r.json.feedback === "mock feedback", r);
r = await call("POST", `/api/projects/${pid}/ai/shot-suggest`, { scriptText: "x" }, token);
check("shot suggest handled", r.status === 200, r);
const sess = (await call("POST", `/api/projects/${pid}/ai/sessions`, { title: "t" }, token)).json.id;
const res = await fetch(`${base}/api/projects/${pid}/ai/chat`, { method: "POST", headers: { "content-type": "application/json", authorization: "Bearer " + token }, body: JSON.stringify({ sessionId: sess, content: "hi", scriptContent: "script" }) });
const text = await res.text();
const events = text.split("\n\n").filter(Boolean).map(e => JSON.parse(e.replace(/^data: /, "")));
const content = events.filter(e => e.content).map(e => e.content).join("");
const done = events.find(e => e.done);
check("chat streamed content", content === "Hello world", { content, events: events.length });
check("chat done event", !!done, events);
const tc = done && JSON.parse(done.message.toolCalls || "[]");
check("tool call reassembled across chunks", tc?.[0]?.function?.name === "edit_script_passage" && tc[0].function.arguments === '{"original_text":"a","replacement_text":"b"}', tc);
r = await call("GET", `/api/projects/${pid}/ai/sessions/${sess}/messages`, undefined, token);
check("messages persisted (user + assistant)", r.json.length === 2, r.json.map(m => m.role));
process.exit(summary() ? 1 : 0);
